services:
  db:
    container_name: honest_pg
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - honest-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  db-test:
    container_name: honest_pg_test
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    volumes:
      - honest-db-test:/var/lib/postgresql/data
    ports:
      - 5433:5432

  adminer:
    container_name: honest_adminer
    depends_on:
      - db
      - db-test
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  honest-db:
  honest-db-test:
